Add files via upload
progenetix/bycon pull request #7
Opened 2021-04-13 09:25 UTC by sofiapfund

Clean version of the publications importing & updating script

2021-04-13 09:40 UTC, mbaudis requested changes

2021-04-13 09:40 UTC, mbaudis commented on byconeer/publicationsUpdater.py
> +path = "/Users/sofiapfund/Desktop/Internship/Scripts/retrieve_publications/publications.txt" ### path of your .tsv file
You still have to make this a command-line option. Please have a look at e.g. variantsExporter (there is only an outfile specified ...), or in general at the args handling (i.e. request file parameter, check if existing -> otherwise terminate w/ warning).

2021-04-13 09:40 UTC, mbaudis commented on byconeer/publicationsUpdater.py
> +    response = requests.get("https://www.ebi.ac.uk/europepmc/webservices/rest/search", params = parameters)
Is there a way to make this an exact match in the query, to really get only the one matching? Otherwise you have to filter the response for the exact PMID (there can be problems with stemming; PMID has no fixed number of digits...).

2021-04-13 09:40 UTC, mbaudis commented on byconeer/publicationsUpdater.py
> +
This and other functions can be moved into byconeer/lib/publication_utils.py and imported from there

2021-04-13 11:11 UTC, sofiapfund commented on byconeer/publicationsUpdater.py
> +    response = requests.get("https://www.ebi.ac.uk/europepmc/webservices/rest/search", params = parameters)
Until now I have only got exact matches. I can however add some lines of code which can check whether the PMID used for querying matches the PMID of the retrieved publication. Only if that is the case the "information" for the next steps is returned.

2021-04-24 09:33 UTC, mbaudis approved these changes
Looking clearer to me now; but I'll just merge to test ...

2021-04-24 09:34 UTC, merged